server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location /api {
        proxy_pass http://student_backend:3007;
    }

    location /about {
        proxy_pass http://student_backend:3007;
    }

    location /health {
        proxy_pass http://student_backend:3007;
    }
}