version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: testdb
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./backend
    container_name: student_backend
    env_file: ./backend/.env
    ports:
      - "3307:3007"
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: student_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  pgdata: