services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: testdb
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d testdb"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: student_backend
    env_file: ./backend/.env
    ports:
      - "3007:3007"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./frontend
    container_name: student_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  pgdata: